### ISSUE TITLE
set up noun-finder

### ISSUE THREAD

**Issue by jfrausto** [jfrausto/FindYourVibe#2]
There is a custom hook that will take the user's input, lowercase their response, split it, then will filter accordingly to the nouns list array and return an array of all matching words. The noun Finder package is said to do most of the functionality that this hook does. The API key takes over a week to come in the email but can buy it for $5. I think it should arrive soon if not it's only $5. I think that this hook can still be used and making additional regex checks should make it function better. 

- [x] Bring in NounFinder npm
- [x] Create Functioning Code Snippet

**Comment by JOCECODE** [comment]
There is a custom hook that will take the user's input, lowercase their response, split it, then will filter accordingly to the nouns list array and return an array of all matching words. The noun Finder package is said to do most of the functionality that this hook does. The API key takes over a week to come in the email but can buy it for $5. I think it should arrive soon if not it's only $5. I think that this hook can still be used and making additional regex checks should make it function better. 

- [ ] Bring in NounFinder npm
- [ ] Create numbers Regex
- [ ] Create Functioning Code Snippet

**Comment by JOCECODE** [comment]
The npm package works through the back end, added code to App.js to console log the words. The custom hook is still in the repo, potential future use for the hook would be a Regex checker to filter out punctuation, symbols, and numbers.
