### ISSUE TITLE
Vibe Check

### ISSUE THREAD

**Issue by JOCECODE** [jfrausto/FindYourVibe#46]
as of right now, The user can save a blurb if they don't select a vibe, it needs a check if the user doesn't select a vibe ask to pick or vibe or post a random vibe. Maybe include a default vibe so if vibe === "" set vibe as 🤐

**Comment by jfrausto** [comment]
logic from disabling buttons could come into play here.

a ternary operator that defaults to that zipped up emoji if there was no vibe in their blurb post

**Comment by JOCECODE** [comment]
I added a ternary operator to check the value of the model if it is an empty string "🤐" else keep same value
