### ISSUE TITLE
Remove or Warn Duplicate Songs in Collections

### ISSUE THREAD

**Issue by mgmoreno22** [jfrausto/FindYourVibe#57]
When song is added to collections, duplicate songs should either not be added or should warn/prompt user about adding a duplicate song.
Potential Error appears when identical IDs are found

**Comment by jfrausto** [comment]
https://levelup.gitconnected.com/7-ways-to-remove-duplicates-from-array-in-javascript-cea4144caf31

theres a section at the bottom of this article titled: Removing Duplicate Objects from a Given Array.
Gonna try that polacode
