### ISSUE TITLE
Home Page Spacing on Small and XS screen 

### ISSUE THREAD

**Issue by mgmoreno22** [jfrausto/FindYourVibe#81]
Minor spacing issue on home page - Ideally title, text, and buttons can have equal or near-equal whitespace on either side 

Potential Fixes:
1) Media query - smallest size reduce left-margin spacing (or percentage)
2) Media query - center text in small screen sizes (removes priority of left margin)
3) Bootstrap Container - may use automatic formatting practices to adjust text sizing

**Comment by JOCECODE** [comment]
I fixed the styling of it I will leave this issue open until we all get a chance to view it.
